const items = [
    {
        id: '001',
        image: 'images/part3/1.webp',
        company: 'DENNISON',
        item_name: 'Men Tapered Fit Formal Trousers',
        original_price: 2799,
        current_price: 783,
        discount_percentage: 72,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 3.5,
            count: 48,
        },
    },
    {
        id: '002',
        image: 'images/part3/2.avif',
        company: 'INVICTUS',
        item_name: 'Slim Fit Cotton Shirt',
        original_price: 2499,
        current_price: 724,
        discount_percentage: 71,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/part3/3.avif',
        company: 'INVICTUS',
        item_name: 'Checked Slim Fit Casual Shirt',
        original_price: 2199,
        current_price: 659,
        discount_percentage: 70,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 3.9,
            count: 1000,
        },
    },
    {
        id: '004',
        image: 'images/part3/4.avif',
        company: 'DENNISON',
        item_name: 'Slim Fit Opaque Party Shirt',
        original_price: 2799,
        current_price: 783,
        discount_percentage: 72,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 4,
            count: 12,
        },
    },
    {
        id: '005',
        image: 'images/part3/5.avif',
        company: 'Hangup',
        item_name: ' Men Chinos Trousers',
        original_price: 2999,
        current_price: 809,
        discount_percentage: 73,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 2.7,
            count: 10,
        },
    },
    {
        id: '006',
        image: 'images/part3/6.jpg',
        company: 'INVICTUS',
        item_name: ' Men Navy Blue Striped Sweatshirt',
        original_price: 1999,
        current_price: 579,
        discount_percentage: 71,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 4.5,
            count: 131,
        },
    },
    {
        id: '007',
        image: 'images/part3/7.jpg',
        company: 'INVICTUS',
        item_name: 'Spread Collar Casual Shirt',
        original_price: 2198,
        current_price: 659,
        discount_percentage: 70,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 3.8,
            count: 5,
        },
    },
    {
        id: '008',
        image: 'images/part3/8.jpg',
        company: 'DENNISON',
        item_name: 'Men Tapered Fit Trousers',
        original_price: 2599,
        current_price: 727,
        discount_percentage: 72,
        return_period: 14,
        delivery_date: '1 March 2024',
        rating: {
            stars: 3.7,
            count: 20,
        },
    }
];